manifest:
  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: claybford
      url-base: https://github.com/claybford
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: claybford #petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    - name: cirque-input-module
      remote: badjeff
      revision: main
  self:
    path: config
